Resources:
  FilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireMealAudioInputs
            Status: Enabled
            Prefix: inputs/
            ExpirationInDays: 7

  MealFileUploadedRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref FilesBucket
          object:
            key:
              - prefix: inputs/
              - prefix: pictures/
      Targets:
        - Id: mealUploaded
          Arn: !GetAtt MealUploadedLambdaFunction.Arn

  MealFileUploadedPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MealUploadedLambdaFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MealFileUploadedRule.Arn
